### ISSUE TITLE
[Bug report] [spark-connector] hive table sort by column is missing

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#3128] opened 2024-04-23 08:47 UTC
### Version

main branch

### Describe what's wrong

hive table sort by column is missing

### Error message and/or stacktrace

no

### How to reproduce

create hive table using spark connector
```sql
CREATE TABLE clustered_by_test2 (ID INT, NAME STRING)
    PARTITIONED BY (YEAR STRING)
    CLUSTERED BY (ID, NAME)
    SORTED BY (ID ASC)
    INTO 3 BUCKETS
    STORED AS PARQUET
```
query hive table using normal spark SQL client:
```
desc table extended clustered_by_test2;
```

sort column is expected to  `Sort Columns        	[`ID`]`, but got `Sort Columns        	[]`

**Comment by SteNicholas** [comment] 2024-05-20 10:00
@FANNG1, could you assign this ticket to me? I have already found the cause of this bug.

**Closed** 2024-05-21 07:34 UTC
Labels: bug
