### ISSUE TITLE
[Bug report] UI:  When the table is clicked, the navigation bar on the left collapses right away

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1997] opened 2024-02-03 01:50 UTC
### Version

main branch

### Describe what's wrong

When I click the table `t1`
![image](https://github.com/datastrato/gravitino/assets/15794564/0932a50d-4ab3-44cd-9acd-301ff0cac1bc)
then
<img width="1869" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/0f0e66fe-4831-4700-987d-955aa41a30f8">

### Error message and/or stacktrace

Please see above.

### How to reproduce

Please see above.

**Comment by yuqi1129** [comment] 2024-02-03 01:51
Besides, the value of comment is empty, can we use N/A or others to replace it?

**Comment by jerryshao** [comment] 2024-02-04 07:04
Cannot reproduce this issue, I'm going to move this out of 0.4.0.

**Comment by jerryshao** [comment] 2024-02-20 03:00
I'm going to close this issue, as this cannot reproduce currently. We can always reopen the issue when it can be reproduced.

**Closed by jerryshao** 2024-02-20 03:00 UTC
Labels: bug
